### PR TITLE
2.12 testing

### PR DESCRIPTION
**Pull request by gundalow**
2.12 testing

### CODE REVIEW

**Comment by webknjaz** [comment]
Wouldn't it be easier if it'd be coming from the shared action? https://github.com/ansible-collections/collection_template/pull/29

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@webknjaz it definitely would be, but I'm not sure how matrixes can be set up by an action. (Also this needs some configurability since different collections, and branches in these collections, will support different sets of stable branches.)

**Comment by webknjaz** [comment]
> @webknjaz it definitely would be, but I'm not sure how matrixes can be set up by an action. (Also this needs some configurability since different collections, and branches in these collections, will support different sets of stable branches.)

This is why I'm starting a reusable workflow — this new feature support job matrices. Moreover, I have a demo with an auto-generated jobs for tox.

**Review by Andersson007 — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@gundalow thanks for the PR! @felixfontein @webknjaz thanks for reviewing!

**Pull request merged**
