### PR TITLE
Add MAINTAINING.md and REVIEW_CHECKLIST.md. Update README.md

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Add MAINTAINING.md and REVIEW_CHECKLIST.md. Update README.md

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Review by gundalow — COMMENTED** [review]
Once this has been reviewed can you please copy the changes to https://github.com/ansible/ansible/pull/74901

**Comment by Andersson007** [comment]
> Once this has been reviewed can you please copy the changes to [ansible/ansible#74901](https://github.com/ansible/ansible/pull/74901)

sure, thanks!

**Comment by russoz** [comment]
Looking good to me :-)

**Comment by Andersson007** [comment]
@russoz @gundalow thanks for reviewing!

**Pull request merged**
