### PR TITLE
A few README updates

### PR DESCRIPTION
**Pull request by briantist**
##### SUMMARY

- news for maintainers correct link
- checklist repo changed `master` to `main`

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@gundalow @Andersson007 PTAL. I would just have merged it, but I don't have permissions for that here :)

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@briantist @felixfontein Thanks :)

Steering Committee now has `write` on this repo

**Comment by felixfontein** [comment]
@briantist @gundalow thanks :)

**Comment by Andersson007** [comment]
@briantist thanks for updating README! @gundalow @felixfontein thanks for reviewing!

@briantist would you like to also suggest your changes in the PR by Ompragash https://github.com/ansible/ansible/pull/74901 ?

**Comment by briantist** [comment]
> @briantist would you like to also suggest your changes in the PR by Ompragash [ansible/ansible#74901](https://github.com/ansible/ansible/pull/74901) ?

Done https://github.com/ansible/ansible/pull/74901#pullrequestreview-877581392

**Pull request merged**
